[project]
name = "mini-chat-fastapi"
version = "0.1.0"
description = ""
authors = [
    {name = "Hayverson",email = "hayversongab@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi (>=0.115,<1.0)",
    "uvicorn[standard] (>=0.34,<1.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=8.3,<9.0)",
    "httpx (>=0.28,<1.0)"
]
