"""adiciona_usuarios_e_fk_jogos

Revision ID: 3de9c80910ce
Revises: 7f7a16c062f9
Create Date: 2026-08-22 15:52:29.428737

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3de9c80910ce'
down_revision: str | None = '7f7a16c062f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=60), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('senha', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.add_column('jogos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'fk_jogos_user_id_usuarios',
        'jogos',
        'usuarios',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_jogos_user_id_usuarios',
        'jogos',
        type_='foreignkey',
    )
    op.drop_column('jogos', 'user_id')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
