"""initial

Revision ID: 7f7a16c062f9
Revises:
Create Date: 2026-08-22 14:22:15.227558

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7f7a16c062f9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'jogos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titulo', sa.String(length=120), nullable=False),
        sa.Column('plataforma', sa.String(length=60), nullable=False),
        sa.Column('genero', sa.String(length=60), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'BACKLOG', 'PLAYING', 'COMPLETED', 'DROPPED', name='statusjogo'
            ),
            nullable=False,
        ),
        sa.Column('horas_jogadas', sa.Float(), nullable=False),
        sa.Column('nota', sa.Float(), nullable=True),
        sa.Column('data_compra', sa.Date(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_jogos_id'), 'jogos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jogos_id'), table_name='jogos')
    op.drop_table('jogos')
    # ### end Alembic commands ###
